CREATE TABLE IF NOT EXISTS public.task_mix_bins (
  "id" bigint generated by default as identity not null,
  "submission_id" bigint,
  "mix_bin1" boolean,
  "mix_bin2" boolean,
  "mix_bin3" boolean,
  "mix_bin4" boolean
);

-- primary key unique index and constraint(s)
ALTER TABLE public.task_mix_bins DROP CONSTRAINT IF EXISTS "task_mix_bins_pkey";
CREATE UNIQUE INDEX IF NOT EXISTS "task_mix_bins_pkey" ON public.task_mix_bins USING btree (id);
ALTER TABLE public.task_mix_bins ADD CONSTRAINT "task_mix_bins_pkey" PRIMARY KEY using index "task_mix_bins_pkey";

-- foreign key constraint: submission
ALTER TABLE public.task_mix_bins DROP CONSTRAINT IF EXISTS "task_mix_bins_submission_id_fkey";
ALTER TABLE public.task_mix_bins ADD CONSTRAINT "task_mix_bins_submission_id_fkey" FOREIGN KEY (submission_id) REFERENCES "public"."Form Submission"(submission_id) not valid;

-- validate parent submission (foreign) keys
ALTER TABLE public.task_mix_bins VALIDATE CONSTRAINT "task_mix_bins_submission_id_fkey";

-- grants (api, user)
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.task_mix_bins
   TO anon, authenticated;

-- grants (supa studio)
GRANT ALL ON TABLE public.task_mix_bins
   TO service_role;

-- PG rls + Policies
ALTER TABLE public.task_mix_bins enable row level security;

DROP POLICY IF EXISTS "Allow Public: Create" ON public.task_mix_bins;
CREATE POLICY "Allow Public: Create"
  ON public.task_mix_bins AS permissive
  FOR insert
  TO public
  with check (true);

DROP POLICY IF EXISTS "Authenticated Dashboard User: Destroy" ON public.task_mix_bins;
CREATE POLICY "Authenticated Dashboard User: Destroy"
  ON public.task_mix_bins AS permissive
  FOR delete
  TO authenticated
  using (true);

DROP POLICY IF EXISTS "Authenticated Dashboard User: View All" ON public.task_mix_bins;
CREATE POLICY "Authenticated Dashboard User: View All"
  ON public.task_mix_bins AS permissive
  FOR select
  TO authenticated
  using (true);

DROP POLICY IF EXISTS "Authenticated Dashboard User: Edit Any" ON public.task_mix_bins;
CREATE POLICY "Authenticated Dashboard User: Edit Any"
  ON public.task_mix_bins AS permissive
  FOR update
  TO authenticated
  using (true)
  with check (true);
