CREATE TABLE "public"."Mixing Bins" (
  "mixing_id" bigint generated by default as identity not null,
  "submission_id" bigint,
  "mix_bin1" boolean,
  "mix_bin2" boolean,
  "mix_bin3" boolean,
  "mix_bin4" boolean
);

ALTER TABLE "public"."Mixing Bins" enable row level security;

CREATE UNIQUE INDEX "Mixing Bins_pkey" ON public."Mixing Bins" USING btree (mixing_id);

ALTER TABLE "public"."Mixing Bins" ADD CONSTRAINT "Mixing Bins_pkey" PRIMARY KEY using index "Mixing Bins_pkey";

ALTER TABLE "public"."Mixing Bins" ADD CONSTRAINT "Mixing Bins_submission_id_fkey" FOREIGN KEY (submission_id) REFERENCES public."Form Submission"(submission_id) not valid;

ALTER TABLE "public"."Mixing Bins" VALIDATE CONSTRAINT "Mixing Bins_submission_id_fkey";

REVOKE ALL ON TABLE public.profiles FROM anon, authenticated;

GRANT ALL ON TABLE public.profiles TO service_role;

CREATE POLICY "Allow insert for Mixing Bins"
  on "public"."Mixing Bins"
  as permissive
  for insert
  to public
with check (true);

CREATE POLICY "dashboard delete mixing bins"
  on "public"."Mixing Bins"
  as permissive
  for delete
  to authenticated
using (true);

CREATE POLICY "dashboard select mixing bins"
  on "public"."Mixing Bins"
  as permissive
  for select
  to authenticated
using (true);

CREATE POLICY "dashboard update mixing bins"
  on "public"."Mixing Bins"
  as permissive
  for update
  to authenticated
using (true)
with check (true);