CREATE TABLE IF NOT EXISTS public.task_sift_compost (
  "id" bigint generated by default as identity not null,
  "submission_id" bigint,
  "all_sifted" boolean
);

-- primary key unique index and constraint(s)
ALTER TABLE public.task_sift_compost DROP CONSTRAINT IF EXISTS "task_sift_compost_pkey";
CREATE UNIQUE INDEX IF NOT EXISTS "task_sift_compost_pkey" ON public.task_sift_compost USING btree (id);
ALTER TABLE public.task_sift_compost ADD CONSTRAINT "task_sift_compost_pkey" PRIMARY KEY using index "task_sift_compost_pkey";

-- foreign key constraint: submission
ALTER TABLE IF EXISTS public.task_sift_compost DROP CONSTRAINT IF EXISTS "task_sift_compost_submission_id_fkey";
ALTER TABLE public.task_sift_compost ADD CONSTRAINT "task_sift_compost_submission_id_fkey" FOREIGN KEY (submission_id) REFERENCES "public"."Form Submission"(submission_id) not valid;

-- validate parent submission (foreign) keys
ALTER TABLE public.task_sift_compost VALIDATE CONSTRAINT "task_sift_compost_submission_id_fkey";

-- grants (api, user)
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.task_sift_compost
   TO anon, authenticated;

-- grants (supa studio)
GRANT ALL ON TABLE public.task_sift_compost
   TO service_role;

-- PG rls + Policies
ALTER TABLE public.task_sift_compost enable row level security;

DROP POLICY IF EXISTS "Allow Public: Create" ON public.task_sift_compost;
CREATE POLICY "Allow Public: Create"
  ON public.task_sift_compost AS permissive
  FOR insert
  TO public
  with check (true);

DROP POLICY IF EXISTS "Authenticated Dashboard User: Destroy" ON public.task_sift_compost;
CREATE POLICY "Authenticated Dashboard User: Destroy"
  ON public.task_sift_compost AS permissive
  FOR delete
  TO authenticated
  using (true);

DROP POLICY IF EXISTS "Authenticated Dashboard User: View All" ON public.task_sift_compost;
CREATE POLICY "Authenticated Dashboard User View All"
  ON public.task_sift_compost AS permissive
  FOR select
  TO authenticated
  using (true);

DROP POLICY IF EXISTS "Authenticated Dashboard User: Edit Any" ON public.task_sift_compost;
CREATE POLICY "Authenticated Dashboard User: Edit Any"
  ON public.task_sift_compost AS permissive
  FOR update
  TO authenticated
  using (true)
  with check (true);
