CREATE TABLE IF NOT EXISTS public.task_supply_water (
  "id" bigint generated by default as identity not null,
  "submission_id" bigint,
  "fill_jugs" boolean,
  "to_barrel" boolean
);

-- primary key unique index and constraint(s)
ALTER TABLE public.task_supply_water DROP CONSTRAINT IF EXISTS "task_supply_water_pkey";
CREATE UNIQUE INDEX IF NOT EXISTS "task_supply_water_pkey" ON public.task_supply_water USING btree (id);
ALTER TABLE public.task_supply_water ADD CONSTRAINT "task_supply_water_pkey" PRIMARY KEY using index "task_supply_water_pkey";

-- foreign key constraint: submission
ALTER TABLE IF EXISTS public.task_supply_water DROP CONSTRAINT IF EXISTS "task_supply_water_submission_id_fkey";
ALTER TABLE public.task_supply_water ADD CONSTRAINT "task_supply_water_submission_id_fkey" FOREIGN KEY (submission_id) REFERENCES "public"."Form Submission"(submission_id) not valid;

-- validate parent submission (foreign) keys
ALTER TABLE public.task_supply_water VALIDATE CONSTRAINT "task_supply_water_submission_id_fkey";

-- grants (api, user)
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.task_supply_water
   TO anon, authenticated;

-- grants (supa studio)
GRANT ALL ON TABLE public.task_supply_water
   TO service_role;

-- PG rls + Policies
ALTER TABLE public.task_supply_water enable row level security;

DROP POLICY IF EXISTS "Allow Public: Create" ON public.task_supply_water;
CREATE POLICY "Allow Public: Create"
  ON public.task_supply_water AS permissive
  FOR insert
  TO public
  with check (true);

DROP POLICY IF EXISTS "Authenticated Dashboard User: Destroy" ON public.task_supply_water;
CREATE POLICY "Authenticated Dashboard User: Destroy"
  ON public.task_supply_water AS permissive
  FOR delete
  TO authenticated
  using (true);

DROP POLICY IF EXISTS "Authenticated Dashboard User: View All" ON public.task_supply_water;
CREATE POLICY "Authenticated Dashboard User View All"
  ON public.task_supply_water AS permissive
  FOR select
  TO authenticated
  using (true);

DROP POLICY IF EXISTS "Authenticated Dashboard User: Edit Any" ON public.task_supply_water;
CREATE POLICY "Authenticated Dashboard User: Edit Any"
  ON public.task_supply_water AS permissive
  FOR update
  TO authenticated
  using (true)
  with check (true);
